import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
IF YOU WANT TO VIEW THE SOURCE CODE, GO TO THE LINK BELOW
*/
`;

const prod = process.argv[2] === "production";

const buildOptions = {
    banner: {
      js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/view",
      "@codemirror/state",
      ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
};

if (!prod) {
    buildOptions.watch = true;
}

esbuild
  .build(buildOptions)
  .catch(() => process.exit(1));

