/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
IF YOU WANT TO VIEW THE SOURCE CODE, GO TO THE LINK BELOW
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MarkdeepSlidesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_path = require("path");
var DEFAULT_SETTINGS = {
  slidesPath: "slides"
};
var SCRIPT_TO_APPEND = `
<script src="markdeep-slides/slides-init.js"><\/script>
`;
var MarkdeepSlidesPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    let timeout;
    this.debouncedGenerateSlides = (editor, view) => {
      clearTimeout(timeout);
      timeout = setTimeout(() => {
        if (view.file) {
          this.generateSlides(view.file, true);
        }
      }, 500);
    };
    this.registerEvent(
      this.app.workspace.on("editor-change", this.debouncedGenerateSlides)
    );
    this.addCommand({
      id: "generate-markdeep-slides",
      name: "Generate Markdeep Slides for current file",
      callback: () => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          this.generateSlides(activeFile, false);
        } else {
          new import_obsidian.Notice("No active file to generate slides from.");
        }
      }
    });
    this.addCommand({
      id: "open-slides-in-browser",
      name: "Open Slides in Browser",
      callback: () => this.openSlidesInBrowser()
    });
    this.addSettingTab(new MarkdeepSlidesSettingTab(this.app, this));
    console.log("Markdeep Slides plugin loaded.");
  }
  onunload() {
    console.log("Markdeep Slides plugin unloaded.");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async openSlidesInBrowser() {
    var _a;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile || activeFile.extension !== "md") {
      new import_obsidian.Notice("No active Markdown file.");
      return;
    }
    const frontmatter = (_a = this.app.metadataCache.getFileCache(activeFile)) == null ? void 0 : _a.frontmatter;
    if (!this.hasMdslidesTag(frontmatter)) {
      new import_obsidian.Notice('File does not have "mdslides" in its tags.');
      return;
    }
    const htmlPath = (0, import_path.join)(this.settings.slidesPath, `${activeFile.basename}.html`);
    const htmlFile = this.app.vault.getAbstractFileByPath(htmlPath);
    if (!htmlFile) {
      await this.generateSlides(activeFile, false);
    }
    const adapter = this.app.vault.adapter;
    if ("getFullPath" in adapter) {
      const fullPath = adapter.getFullPath(htmlPath);
      const command = this.getOpenCommand(fullPath);
      if (command) {
        require("child_process").exec(command, (err) => {
          if (err) {
            console.error("Error opening file in browser:", err);
            new import_obsidian.Notice("Failed to open file in browser.");
          }
        });
      }
    } else {
      new import_obsidian.Notice("This feature is not supported on your platform.");
    }
  }
  getOpenCommand(filePath) {
    const platform = process.platform;
    const sanitizedPath = `"${filePath}"`;
    if (platform === "darwin") {
      return `open ${sanitizedPath}`;
    }
    if (platform === "win32") {
      return `start ${sanitizedPath}`;
    }
    if (platform === "linux") {
      return `xdg-open ${sanitizedPath}`;
    }
    return null;
  }
  async generateSlides(file, isAuto) {
    if (!file || file.extension !== "md") {
      return;
    }
    const fileCache = this.app.metadataCache.getFileCache(file);
    const frontmatter = fileCache == null ? void 0 : fileCache.frontmatter;
    if (!this.hasMdslidesTag(frontmatter)) {
      if (!isAuto) {
        new import_obsidian.Notice('File does not have "mdslides" in its tags. Slides not generated.');
      }
      return;
    }
    try {
      const fileContent = await this.app.vault.read(file);
      const frontmatterRegex = /^---\s*[\s\S]*?---\s*/;
      const content = fileContent.replace(frontmatterRegex, "");
      const finalHtml = content + SCRIPT_TO_APPEND;
      const outputDir = this.settings.slidesPath;
      const outputFileName = `${file.basename}.html`;
      const outputPath = (0, import_path.join)(outputDir, outputFileName);
      try {
        await this.app.vault.createFolder(outputDir);
      } catch (e) {
      }
      const existingFile = this.app.vault.getAbstractFileByPath(outputPath);
      if (existingFile && existingFile instanceof import_obsidian.TFile) {
        await this.app.vault.modify(existingFile, finalHtml);
      } else {
        await this.app.vault.create(outputPath, finalHtml);
      }
      if (!isAuto) {
        new import_obsidian.Notice(`Slides generated successfully at: ${outputPath}`);
      }
      console.log(`Slides for ${file.basename} processed.`);
    } catch (error) {
      console.error("Error generating slides:", error);
      if (!isAuto) {
        new import_obsidian.Notice("Failed to generate slides. See console for details.");
      }
    }
  }
  hasMdslidesTag(frontmatter) {
    if (!frontmatter || !frontmatter.tags) {
      return false;
    }
    const tags = frontmatter.tags;
    if (typeof tags === "string") {
      return tags.split(",").map((t) => t.trim()).includes("mdslides");
    }
    if (Array.isArray(tags)) {
      return tags.includes("mdslides");
    }
    return false;
  }
};
var MarkdeepSlidesSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Markdeep Slides Settings" });
    new import_obsidian.Setting(containerEl).setName("Slides output path").setDesc("The vault path to save the generated HTML slide files.").addText((text) => text.setPlaceholder("e.g., slides").setValue(this.plugin.settings.slidesPath).onChange(async (value) => {
      this.plugin.settings.slidesPath = value;
      await this.plugin.saveSettings();
    }));
  }
};
